
PN = "mingw-filesystem"
PE = "0"
PV = "148"
PR = "7.el10"
PACKAGES = "mingw-filesystem-base mingw32-filesystem mingw64-filesystem ucrt64-filesystem"


URI_mingw-filesystem-base = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw-filesystem-base-148-7.el10.noarch.rpm;unpack=0"
RDEPENDS:mingw-filesystem-base = "/usr/bin/sh ( ) /usr/bin/bash ( ) redhat-rpm-config ( ) cmake-rpm-macros ( ) pkgconf ( )"
RPROVIDES:mingw-filesystem-base = "rpm_macro(mingw_build_targets) ( ) rpm_macro(mingw_build_ucrt64) ( ) rpm_macro(mingw_build_win32) ( ) rpm_macro(mingw_build_win64) ( ) rpm_macro(mingw_cmake) ( ) rpm_macro(mingw_configure) ( ) rpm_macro(mingw_debug_install_post) ( ) rpm_macro(mingw_debug_package) ( ) rpm_macro(mingw_find_lang) ( ) rpm_macro(mingw_finddebuginfo) ( ) rpm_macro(mingw_make) ( ) rpm_macro(mingw_make_build) ( ) rpm_macro(mingw_make_install) ( ) rpm_macro(mingw_meson) ( ) rpm_macro(mingw_ninja) ( ) rpm_macro(mingw_ninja_install) ( ) rpm_macro(mingw_nm) ( ) rpm_macro(mingw_objcopy) ( ) rpm_macro(mingw_objdump) ( ) rpm_macro(mingw_package_header) ( ) rpm_macro(mingw_qmake_qt5) ( ) rpm_macro(mingw_qmake_qt6) ( ) rpm_macro(mingw_strip) ( ) mingw-filesystem-base ( =  148-7.el10) config(mingw-filesystem-base) ( =  148-7.el10)"

URI_mingw32-filesystem = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw32-filesystem-148-7.el10.noarch.rpm;unpack=0"
RDEPENDS:mingw32-filesystem = "mingw-binutils-generic ( ) mingw-filesystem-base ( =  148-7.el10)"
RPROVIDES:mingw32-filesystem = "rpm_macro(mingw32_addr2line) ( ) rpm_macro(mingw32_ar) ( ) rpm_macro(mingw32_as) ( ) rpm_macro(mingw32_bindir) ( ) rpm_macro(mingw32_cc) ( ) rpm_macro(mingw32_cflags) ( ) rpm_macro(mingw32_cmake) ( ) rpm_macro(mingw32_cmake_generic) ( ) rpm_macro(mingw32_configure) ( ) rpm_macro(mingw32_cpp) ( ) rpm_macro(mingw32_cppflags) ( ) rpm_macro(mingw32_cxx) ( ) rpm_macro(mingw32_datadir) ( ) rpm_macro(mingw32_debug_package) ( ) rpm_macro(mingw32_description) ( ) rpm_macro(mingw32_dlltool) ( ) rpm_macro(mingw32_dllwrap) ( ) rpm_macro(mingw32_docdir) ( ) rpm_macro(mingw32_env) ( ) rpm_macro(mingw32_exec_prefix) ( ) rpm_macro(mingw32_fflags) ( ) rpm_macro(mingw32_gcov) ( ) rpm_macro(mingw32_gprof) ( ) rpm_macro(mingw32_host) ( ) rpm_macro(mingw32_includedir) ( ) rpm_macro(mingw32_infodir) ( ) rpm_macro(mingw32_ld) ( ) rpm_macro(mingw32_ldflags) ( ) rpm_macro(mingw32_libdir) ( ) rpm_macro(mingw32_libexecdir) ( ) rpm_macro(mingw32_localstatedir) ( ) rpm_macro(mingw32_make) ( ) rpm_macro(mingw32_mandir) ( ) rpm_macro(mingw32_meson) ( ) rpm_macro(mingw32_nm) ( ) rpm_macro(mingw32_objcopy) ( ) rpm_macro(mingw32_objdump) ( ) rpm_macro(mingw32_pkg_config) ( ) rpm_macro(mingw32_pkg_name) ( ) rpm_macro(mingw32_pkgconfig_personalitydir) ( ) rpm_macro(mingw32_prefix) ( ) rpm_macro(mingw32_qmake_qt5) ( ) rpm_macro(mingw32_qmake_qt6) ( ) rpm_macro(mingw32_ranlib) ( ) rpm_macro(mingw32_readelf) ( ) rpm_macro(mingw32_rustflags) ( ) rpm_macro(mingw32_sbindir) ( ) rpm_macro(mingw32_sharedstatedir) ( ) rpm_macro(mingw32_size) ( ) rpm_macro(mingw32_strings) ( ) rpm_macro(mingw32_strip) ( ) rpm_macro(mingw32_sysconfdir) ( ) rpm_macro(mingw32_sysroot) ( ) rpm_macro(mingw32_target) ( ) rpm_macro(mingw32_windmc) ( ) rpm_macro(mingw32_windres) ( ) config(mingw32-filesystem) ( =  148-7.el10) mingw32-filesystem ( =  148-7.el10) mingw32-pkg-config ( =  0.28-17)"

URI_mingw64-filesystem = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/mingw64-filesystem-148-7.el10.noarch.rpm;unpack=0"
RDEPENDS:mingw64-filesystem = "mingw-binutils-generic ( ) mingw-filesystem-base ( =  148-7.el10)"
RPROVIDES:mingw64-filesystem = "rpm_macro(mingw64_addr2line) ( ) rpm_macro(mingw64_ar) ( ) rpm_macro(mingw64_as) ( ) rpm_macro(mingw64_bindir) ( ) rpm_macro(mingw64_cc) ( ) rpm_macro(mingw64_cflags) ( ) rpm_macro(mingw64_cmake) ( ) rpm_macro(mingw64_cmake_generic) ( ) rpm_macro(mingw64_configure) ( ) rpm_macro(mingw64_cpp) ( ) rpm_macro(mingw64_cppflags) ( ) rpm_macro(mingw64_cxx) ( ) rpm_macro(mingw64_datadir) ( ) rpm_macro(mingw64_debug_package) ( ) rpm_macro(mingw64_description) ( ) rpm_macro(mingw64_dlltool) ( ) rpm_macro(mingw64_dllwrap) ( ) rpm_macro(mingw64_docdir) ( ) rpm_macro(mingw64_env) ( ) rpm_macro(mingw64_exec_prefix) ( ) rpm_macro(mingw64_fflags) ( ) rpm_macro(mingw64_gcov) ( ) rpm_macro(mingw64_gprof) ( ) rpm_macro(mingw64_host) ( ) rpm_macro(mingw64_includedir) ( ) rpm_macro(mingw64_infodir) ( ) rpm_macro(mingw64_ld) ( ) rpm_macro(mingw64_ldflags) ( ) rpm_macro(mingw64_libdir) ( ) rpm_macro(mingw64_libexecdir) ( ) rpm_macro(mingw64_localstatedir) ( ) rpm_macro(mingw64_make) ( ) rpm_macro(mingw64_mandir) ( ) rpm_macro(mingw64_meson) ( ) rpm_macro(mingw64_nm) ( ) rpm_macro(mingw64_objcopy) ( ) rpm_macro(mingw64_objdump) ( ) rpm_macro(mingw64_pkg_config) ( ) rpm_macro(mingw64_pkg_name) ( ) rpm_macro(mingw64_pkgconfig_personalitydir) ( ) rpm_macro(mingw64_prefix) ( ) rpm_macro(mingw64_qmake_qt5) ( ) rpm_macro(mingw64_qmake_qt6) ( ) rpm_macro(mingw64_ranlib) ( ) rpm_macro(mingw64_readelf) ( ) rpm_macro(mingw64_rustflags) ( ) rpm_macro(mingw64_sbindir) ( ) rpm_macro(mingw64_sharedstatedir) ( ) rpm_macro(mingw64_size) ( ) rpm_macro(mingw64_strings) ( ) rpm_macro(mingw64_strip) ( ) rpm_macro(mingw64_sysconfdir) ( ) rpm_macro(mingw64_sysroot) ( ) rpm_macro(mingw64_target) ( ) rpm_macro(mingw64_windmc) ( ) rpm_macro(mingw64_windres) ( ) config(mingw64-filesystem) ( =  148-7.el10) mingw64-filesystem ( =  148-7.el10) mingw64-pkg-config ( =  0.28-17)"

URI_ucrt64-filesystem = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/ucrt64-filesystem-148-7.el10.noarch.rpm;unpack=0"
RDEPENDS:ucrt64-filesystem = "mingw-binutils-generic ( ) mingw-filesystem-base ( =  148-7.el10)"
RPROVIDES:ucrt64-filesystem = "rpm_macro(ucrt64_addr2line) ( ) rpm_macro(ucrt64_ar) ( ) rpm_macro(ucrt64_as) ( ) rpm_macro(ucrt64_bindir) ( ) rpm_macro(ucrt64_cc) ( ) rpm_macro(ucrt64_cflags) ( ) rpm_macro(ucrt64_cmake) ( ) rpm_macro(ucrt64_cmake_generic) ( ) rpm_macro(ucrt64_cmake_kde4) ( ) rpm_macro(ucrt64_configure) ( ) rpm_macro(ucrt64_cpp) ( ) rpm_macro(ucrt64_cppflags) ( ) rpm_macro(ucrt64_cxx) ( ) rpm_macro(ucrt64_datadir) ( ) rpm_macro(ucrt64_debug_package) ( ) rpm_macro(ucrt64_description) ( ) rpm_macro(ucrt64_dlltool) ( ) rpm_macro(ucrt64_dllwrap) ( ) rpm_macro(ucrt64_docdir) ( ) rpm_macro(ucrt64_env) ( ) rpm_macro(ucrt64_exec_prefix) ( ) rpm_macro(ucrt64_gcov) ( ) rpm_macro(ucrt64_gprof) ( ) rpm_macro(ucrt64_host) ( ) rpm_macro(ucrt64_includedir) ( ) rpm_macro(ucrt64_infodir) ( ) rpm_macro(ucrt64_ld) ( ) rpm_macro(ucrt64_ldflags) ( ) rpm_macro(ucrt64_libdir) ( ) rpm_macro(ucrt64_libexecdir) ( ) rpm_macro(ucrt64_localstatedir) ( ) rpm_macro(ucrt64_make) ( ) rpm_macro(ucrt64_mandir) ( ) rpm_macro(ucrt64_meson) ( ) rpm_macro(ucrt64_nm) ( ) rpm_macro(ucrt64_objcopy) ( ) rpm_macro(ucrt64_objdump) ( ) rpm_macro(ucrt64_pkg_config) ( ) rpm_macro(ucrt64_pkg_name) ( ) rpm_macro(ucrt64_pkgconfig_personalitydir) ( ) rpm_macro(ucrt64_prefix) ( ) rpm_macro(ucrt64_qmake_qt5) ( ) rpm_macro(ucrt64_ranlib) ( ) rpm_macro(ucrt64_readelf) ( ) rpm_macro(ucrt64_sbindir) ( ) rpm_macro(ucrt64_sharedstatedir) ( ) rpm_macro(ucrt64_size) ( ) rpm_macro(ucrt64_strings) ( ) rpm_macro(ucrt64_strip) ( ) rpm_macro(ucrt64_sysconfdir) ( ) rpm_macro(ucrt64_sysroot) ( ) rpm_macro(ucrt64_target) ( ) rpm_macro(ucrt64_windmc) ( ) rpm_macro(ucrt64_windres) ( ) config(ucrt64-filesystem) ( =  148-7.el10) ucrt64-filesystem ( =  148-7.el10) ucrt64-pkg-config ( =  0.28-17)"
