
PN = "perl-Software-License"
PE = "0"
PV = "0.104006"
PR = "4.el10"
PACKAGES = "perl-Software-License perl-Software-License-tests"


URI_perl-Software-License = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-Software-License-0.104006-4.el10.noarch.rpm;unpack=0"
RDEPENDS:perl-Software-License = "perl(strict) ( ) perl-libs ( ) perl(warnings) ( ) perl(Carp) ( ) perl(File::Spec) ( ) perl(parent) ( ) perl(utf8) ( ) perl(Module::Load) ( ) perl(IO::Dir) ( ) perl(Software::License) ( ) perl(Text::Template) ( ) perl(Data::Section) ( ) perl(Software::License::Artistic_1_0_Perl) ( ) perl(Software::License::GPL_1) ( ) perl(Software::License::GPL_3) ( ) perl(Software::License::SSLeay) ( )"
RPROVIDES:perl-Software-License = "perl(Software::License) ( =  0.104006) perl(Software::License::AGPL_3) ( =  0.104006) perl(Software::License::Apache_1_1) ( =  0.104006) perl(Software::License::Apache_2_0) ( =  0.104006) perl(Software::License::Artistic_1_0) ( =  0.104006) perl(Software::License::Artistic_1_0_Perl) ( =  0.104006) perl(Software::License::Artistic_2_0) ( =  0.104006) perl(Software::License::BSD) ( =  0.104006) perl(Software::License::CC0_1_0) ( =  0.104006) perl(Software::License::Custom) ( =  0.104006) perl(Software::License::EUPL_1_1) ( =  0.104006) perl(Software::License::EUPL_1_2) ( =  0.104006) perl(Software::License::FreeBSD) ( =  0.104006) perl(Software::License::GFDL_1_2) ( =  0.104006) perl(Software::License::GFDL_1_3) ( =  0.104006) perl(Software::License::GPL_1) ( =  0.104006) perl(Software::License::GPL_2) ( =  0.104006) perl(Software::License::GPL_3) ( =  0.104006) perl(Software::License::ISC) ( =  0.104006) perl(Software::License::LGPL_2_1) ( =  0.104006) perl(Software::License::LGPL_3_0) ( =  0.104006) perl(Software::License::MIT) ( =  0.104006) perl(Software::License::Mozilla_1_0) ( =  0.104006) perl(Software::License::Mozilla_1_1) ( =  0.104006) perl(Software::License::Mozilla_2_0) ( =  0.104006) perl(Software::License::None) ( =  0.104006) perl(Software::License::OpenSSL) ( =  0.104006) perl(Software::License::Perl_5) ( =  0.104006) perl(Software::License::PostgreSQL) ( =  0.104006) perl(Software::License::QPL_1_0) ( =  0.104006) perl(Software::License::SSLeay) ( =  0.104006) perl(Software::License::Sun) ( =  0.104006) perl(Software::License::Zlib) ( =  0.104006) perl(Software::LicenseUtils) ( =  0.104006) perl-Software-License ( =  0.104006-4.el10)"

URI_perl-Software-License-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Software-License-tests-0.104006-4.el10.noarch.rpm;unpack=0"
RDEPENDS:perl-Software-License-tests = "perl(strict) ( ) /usr/bin/perl ( ) /usr/bin/sh ( ) perl-Test-Harness ( ) perl(warnings) ( ) perl(Test::More) ( ) perl(File::Spec) ( ) perl(ExtUtils::MakeMaker) ( ) perl(Try::Tiny) ( ) perl(Software::License) ( ) perl(Software::License::AGPL_3) ( ) perl(Software::License::Apache_1_1) ( ) perl(Software::License::Apache_2_0) ( ) perl(Software::License::Artistic_1_0) ( ) perl(Software::License::Artistic_2_0) ( ) perl(Software::License::BSD) ( ) perl(Software::License::CC0_1_0) ( ) perl(Software::License::Custom) ( ) perl(Software::License::EUPL_1_1) ( ) perl(Software::License::EUPL_1_2) ( ) perl(Software::License::FreeBSD) ( ) perl(Software::License::GFDL_1_2) ( ) perl(Software::License::GFDL_1_3) ( ) perl(Software::License::GPL_1) ( ) perl(Software::License::GPL_2) ( ) perl(Software::License::GPL_3) ( ) perl(Software::License::LGPL_2_1) ( ) perl(Software::License::LGPL_3_0) ( ) perl(Software::License::MIT) ( ) perl(Software::License::Mozilla_1_0) ( ) perl(Software::License::Mozilla_1_1) ( ) perl(Software::License::Mozilla_2_0) ( ) perl(Software::License::OpenSSL) ( ) perl(Software::License::PostgreSQL) ( ) perl(Software::License::QPL_1_0) ( ) perl(Software::License::Zlib) ( ) perl(Software::LicenseUtils) ( ) perl-Software-License ( =  0.104006-4.el10)"
RPROVIDES:perl-Software-License-tests = "perl-Software-License-tests ( =  0.104006-4.el10)"
