
PN = "perl-DBI"
PE = "0"
PV = "1.643"
PR = "26.el10"
PACKAGES = "perl-DBI perl-DBI-tests"


URI_perl-DBI = "https://vault.almalinux.org/10.0/AppStream/x86_64_v2/os/Packages/perl-DBI-1.643-26.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:perl-DBI = "rtld(GNU_HASH) ( ) libc.so.6(GLIBC_2.38)(64bit) ( ) perl(strict) ( ) perl-libs ( ) perl(warnings) ( ) perl(Carp) ( ) perl(Exporter) ( ) libperl.so.5.40()(64bit) ( ) /usr/bin/perl ( ) perl(vars) ( ) perl(constant) ( ) perl(File::Spec) ( ) perl(Config) ( ) perl(File::Basename) ( ) perl(Getopt::Long) ( ) perl(:MODULE_COMPAT_5.40.0) ( ) perl(Cwd) ( ) perl(Fcntl) ( ) perl(Scalar::Util) ( ) perl(base) ( ) perl(Data::Dumper) ( ) perl(Symbol) ( ) perl(IO::File) ( ) perl(DynaLoader) ( ) perl(Errno) ( ) perl(Tie::Hash) ( ) perl(utf8) ( ) perl(DBI) ( ) perl(FileHandle) ( ) perl(Storable) ( ) perl(IO::Select) ( ) perl(IPC::Open3) ( ) perl(Math::BigInt) ( ) perl(UNIVERSAL) ( ) perl(DBI::Const::GetInfoType) ( ) perl(IO::Dir) ( ) perl(DBD::File) ( ) perl(DBD::Gofer::Policy::Base) ( ) perl(DBD::Gofer::Transport::Base) ( ) perl(DBD::Gofer::Transport::pipeone) ( ) perl(DBI::Const::GetInfo::ANSI) ( ) perl(DBI::Const::GetInfo::ODBC) ( ) perl(DBI::DBD::SqlEngine) ( ) perl(DBI::Gofer::Execute) ( ) perl(DBI::Gofer::Request) ( ) perl(DBI::Gofer::Response) ( ) perl(DBI::Gofer::Serializer::Base) ( ) perl(DBI::Gofer::Serializer::DataDumper) ( ) perl(DBI::Gofer::Serializer::Storable) ( ) perl(DBI::Gofer::Transport::Base) ( ) perl(DBI::Gofer::Transport::pipeone) ( ) perl(DBI::Profile) ( ) perl(DBI::ProfileData) ( ) perl(DBI::ProfileDumper) ( ) perl(DBI::SQL::Nano) ( ) perl(DBI::Util::_accessor) ( ) perl(:VERSION) ( >=  5.8.0)"
RPROVIDES:perl-DBI = "perl(DBD::DBM::Statement) ( ) perl(DBD::DBM::Table) ( ) perl(DBD::DBM::db) ( ) perl(DBD::DBM::dr) ( ) perl(DBD::DBM::st) ( ) perl(DBD::File::DataSource::File) ( ) perl(DBD::File::DataSource::Stream) ( ) perl(DBD::File::Statement) ( ) perl(DBD::File::Table) ( ) perl(DBD::File::TableSource::FileSystem) ( ) perl(DBD::File::db) ( ) perl(DBD::File::dr) ( ) perl(DBD::File::st) ( ) perl(DBD::Mem::DataSource) ( ) perl(DBD::Mem::Statement) ( ) perl(DBD::Mem::Table) ( ) perl(DBD::Mem::db) ( ) perl(DBD::Mem::dr) ( ) perl(DBD::Mem::st) ( ) perl(DBDI) ( ) perl(DBI::DBD::SqlEngine::DataSource) ( ) perl(DBI::DBD::SqlEngine::Statement) ( ) perl(DBI::DBD::SqlEngine::Table) ( ) perl(DBI::DBD::SqlEngine::TableSource) ( ) perl(DBI::DBD::SqlEngine::TieMeta) ( ) perl(DBI::DBD::SqlEngine::TieTables) ( ) perl(DBI::DBD::SqlEngine::db) ( ) perl(DBI::DBD::SqlEngine::dr) ( ) perl(DBI::DBD::SqlEngine::st) ( ) perl(DBI::SQL::Nano::Statement_) ( ) perl(DBI::SQL::Nano::Table_) ( ) perl(DBI::common) ( ) perl(DBD::DBM) ( =  0.08) perl(DBD::ExampleP) ( =  12.014311) perl(DBD::File) ( =  0.44) perl(DBD::Gofer) ( =  0.015327) perl(DBD::Gofer::Policy::Base) ( =  0.010088) perl(DBD::Gofer::Policy::classic) ( =  0.010088) perl(DBD::Gofer::Policy::pedantic) ( =  0.010088) perl(DBD::Gofer::Policy::rush) ( =  0.010088) perl(DBD::Gofer::Transport::Base) ( =  0.014121) perl(DBD::Gofer::Transport::null) ( =  0.010088) perl(DBD::Gofer::Transport::pipeone) ( =  0.010088) perl(DBD::Gofer::Transport::stream) ( =  0.014599) perl(DBD::Mem) ( =  0.001) perl(DBD::NullP) ( =  12.014715) perl(DBD::Sponge) ( =  12.010003) perl(DBI) ( =  1.643) perl(DBI::Const::GetInfo::ANSI) ( =  2.008697) perl(DBI::Const::GetInfo::ODBC) ( =  2.011374) perl(DBI::Const::GetInfoReturn) ( =  2.008697) perl(DBI::Const::GetInfoType) ( =  2.008697) perl(DBI::DBD) ( =  12.015129) perl(DBI::DBD::Metadata) ( =  2.014214) perl(DBI::DBD::SqlEngine) ( =  0.06) perl(DBI::Gofer::Execute) ( =  0.014283) perl(DBI::Gofer::Request) ( =  0.012537) perl(DBI::Gofer::Response) ( =  0.011566) perl(DBI::Gofer::Serializer::Base) ( =  0.009950) perl(DBI::Gofer::Serializer::DataDumper) ( =  0.009950) perl(DBI::Gofer::Serializer::Storable) ( =  0.015586) perl(DBI::Gofer::Transport::Base) ( =  0.012537) perl(DBI::Gofer::Transport::pipeone) ( =  0.012537) perl(DBI::Gofer::Transport::stream) ( =  0.012537) perl(DBI::Profile) ( =  2.015065) perl(DBI::ProfileData) ( =  2.010008) perl(DBI::ProfileDumper) ( =  2.015325) perl(DBI::ProfileDumper::Apache) ( =  2.014121) perl(DBI::ProfileSubs) ( =  0.009396) perl(DBI::SQL::Nano) ( =  1.015544) perl(DBI::Util::CacheMemory) ( =  0.010315) perl(DBI::Util::_accessor) ( =  0.009479) perl-DBI ( =  1.643-26.el10) perl-DBI(x86-64) ( =  1.643-26.el10)"

URI_perl-DBI-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-DBI-tests-1.643-26.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:perl-DBI-tests = "perl(strict) ( ) /usr/bin/perl ( ) perl-Test-Harness ( ) perl(warnings) ( ) /usr/bin/bash ( ) perl(File::Spec) ( ) perl(Config) ( ) perl(vars) ( ) perl(base) ( ) perl(Cwd) ( ) perl(Data::Dumper) ( ) perl(overload) ( ) perl(File::Path) ( ) perl(constant) ( ) perl(File::Basename) ( ) perl(Scalar::Util) ( ) perl(Getopt::Long) ( ) perl(Symbol) ( ) perl(threads) ( ) perl(B) ( ) perl(File::Copy) ( ) perl(Tie::Hash) ( ) perl(Storable) ( ) perl(Benchmark) ( ) perl(DBD::DBM) ( ) perl(DBI::Profile) ( ) perl(DBI::Util::CacheMemory) ( ) perl-DBI ( =  1.643-26.el10) perl(DBI) ( >=  1.50) perl(Test::More) ( >=  0.84)"
RPROVIDES:perl-DBI-tests = "perl-DBI-tests ( =  1.643-26.el10) perl-DBI-tests(x86-64) ( =  1.643-26.el10)"
