
PN = "perl-Test-Deep"
PE = "0"
PV = "1.204"
PR = "9.el10"
PACKAGES = "perl-Test-Deep perl-Test-Deep-tests"


URI_perl-Test-Deep = "https://vault.almalinux.org/10.0/CRB/x86_64_v2/os/Packages/perl-Test-Deep-1.204-9.el10.noarch.rpm;unpack=0"
RDEPENDS:perl-Test-Deep = "perl(strict) ( ) perl-libs ( ) perl(warnings) ( ) perl(Exporter) ( ) perl(Carp) ( ) perl(base) ( ) perl(Scalar::Util) ( ) perl(Test::Builder) ( ) perl(overload) ( ) perl(Test::Deep::Array) ( ) perl(Test::Deep::Cache) ( ) perl(Test::Deep::Cache::Simple) ( ) perl(Test::Deep::Cmp) ( ) perl(Test::Deep::MM) ( ) perl(Test::Deep::Methods) ( ) perl(Test::Deep::Ref) ( ) perl(Test::Deep::RegexpMatches) ( ) perl(Test::Deep::RegexpVersion) ( ) perl(Test::Deep::Stack) ( ) perl(:VERSION) ( >=  5.10.0)"
RPROVIDES:perl-Test-Deep = "perl(Test::Deep) ( =  1.204) perl(Test::Deep::All) ( =  1.204) perl(Test::Deep::Any) ( =  1.204) perl(Test::Deep::Array) ( =  1.204) perl(Test::Deep::ArrayEach) ( =  1.204) perl(Test::Deep::ArrayElementsOnly) ( =  1.204) perl(Test::Deep::ArrayLength) ( =  1.204) perl(Test::Deep::ArrayLengthOnly) ( =  1.204) perl(Test::Deep::Blessed) ( =  1.204) perl(Test::Deep::Boolean) ( =  1.204) perl(Test::Deep::Cache) ( =  1.204) perl(Test::Deep::Cache::Simple) ( =  1.204) perl(Test::Deep::Class) ( =  1.204) perl(Test::Deep::Cmp) ( =  1.204) perl(Test::Deep::Code) ( =  1.204) perl(Test::Deep::Hash) ( =  1.204) perl(Test::Deep::HashEach) ( =  1.204) perl(Test::Deep::HashElements) ( =  1.204) perl(Test::Deep::HashKeys) ( =  1.204) perl(Test::Deep::HashKeysOnly) ( =  1.204) perl(Test::Deep::Ignore) ( =  1.204) perl(Test::Deep::Isa) ( =  1.204) perl(Test::Deep::ListMethods) ( =  1.204) perl(Test::Deep::MM) ( =  1.204) perl(Test::Deep::Methods) ( =  1.204) perl(Test::Deep::NoTest) ( =  1.204) perl(Test::Deep::None) ( =  1.204) perl(Test::Deep::Number) ( =  1.204) perl(Test::Deep::Obj) ( =  1.204) perl(Test::Deep::Ref) ( =  1.204) perl(Test::Deep::RefType) ( =  1.204) perl(Test::Deep::Regexp) ( =  1.204) perl(Test::Deep::RegexpMatches) ( =  1.204) perl(Test::Deep::RegexpOnly) ( =  1.204) perl(Test::Deep::RegexpRef) ( =  1.204) perl(Test::Deep::RegexpRefOnly) ( =  1.204) perl(Test::Deep::RegexpVersion) ( =  1.204) perl(Test::Deep::ScalarRef) ( =  1.204) perl(Test::Deep::ScalarRefOnly) ( =  1.204) perl(Test::Deep::Set) ( =  1.204) perl(Test::Deep::Shallow) ( =  1.204) perl(Test::Deep::Stack) ( =  1.204) perl(Test::Deep::String) ( =  1.204) perl(Test::Deep::SubHash) ( =  1.204) perl(Test::Deep::SubHashElements) ( =  1.204) perl(Test::Deep::SubHashKeys) ( =  1.204) perl(Test::Deep::SubHashKeysOnly) ( =  1.204) perl(Test::Deep::SuperHash) ( =  1.204) perl(Test::Deep::SuperHashElements) ( =  1.204) perl(Test::Deep::SuperHashKeys) ( =  1.204) perl(Test::Deep::SuperHashKeysOnly) ( =  1.204) perl-Test-Deep ( =  1.204-9.el10)"

URI_perl-Test-Deep-tests = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/perl-Test-Deep-tests-1.204-9.el10.noarch.rpm;unpack=0"
RDEPENDS:perl-Test-Deep-tests = "perl(strict) ( ) /usr/bin/perl ( ) /usr/bin/sh ( ) perl-Test-Harness ( ) perl(warnings) ( ) perl(lib) ( ) perl(base) ( ) perl(overload) ( ) perl(Scalar::Util) ( ) perl(if) ( ) perl(Test::Deep) ( ) perl(Test::Tester) ( ) perl(Test::Deep::Cache) ( ) perl(Test::Deep::NoTest) ( ) perl(Test::More) ( >=  0.88) perl-Test-Deep ( =  1.204-9.el10)"
RPROVIDES:perl-Test-Deep-tests = "perl-Test-Deep-tests ( =  1.204-9.el10)"
