
PN = "sblim-gather"
PE = "0"
PV = "2.2.9"
PR = "33.el10"
PACKAGES = "sblim-gather sblim-gather-devel sblim-gather-provider sblim-gather-test"


URI_sblim-gather = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sblim-gather-2.2.9-33.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:sblim-gather = "/bin/sh ( ) systemd ( ) rtld(GNU_HASH) ( ) libgcc_s.so.1()(64bit) ( ) libgcc_s.so.1(GCC_3.0)(64bit) ( ) libgcc_s.so.1(GCC_3.3.1)(64bit) ( ) libc.so.6(GLIBC_2.34)(64bit) ( ) libm.so.6()(64bit) ( ) cim-server ( ) libvirt.so.0()(64bit) ( ) libvirt.so.0(LIBVIRT_0.0.3)(64bit) ( ) libvirt.so.0(LIBVIRT_0.1.0)(64bit) ( ) libvirt.so.0(LIBVIRT_0.1.1)(64bit) ( ) libvirt.so.0(LIBVIRT_0.3.2)(64bit) ( ) libvirt.so.0(LIBVIRT_0.1.5)(64bit) ( ) libvirt.so.0(LIBVIRT_0.3.3)(64bit) ( ) libvirt.so.0(LIBVIRT_0.8.1)(64bit) ( )"
RPROVIDES:sblim-gather = "libgatherutil.so.0()(64bit) ( ) libmcserv.so.0()(64bit) ( ) librcserv.so.0()(64bit) ( ) librgather.so.0()(64bit) ( ) librrepos.so.0()(64bit) ( ) libgather.so.0()(64bit) ( ) librepos.so.0()(64bit) ( ) libmetricIPProtocolEndpoint.so()(64bit) ( ) libmetricKvm.so()(64bit) ( ) libmetricLocalFileSystem.so()(64bit) ( ) libmetricNetworkPort.so()(64bit) ( ) libmetricOperatingSystem.so()(64bit) ( ) libmetricProcessor.so()(64bit) ( ) libmetricStorage.so()(64bit) ( ) libmetricUnixProcess.so()(64bit) ( ) libmetricXen.so()(64bit) ( ) librepositoryIPProtocolEndpoint.so()(64bit) ( ) librepositoryKvm.so()(64bit) ( ) librepositoryLocalFileSystem.so()(64bit) ( ) librepositoryNetworkPort.so()(64bit) ( ) librepositoryOperatingSystem.so()(64bit) ( ) librepositoryProcessor.so()(64bit) ( ) librepositoryStorage.so()(64bit) ( ) librepositoryUnixProcess.so()(64bit) ( ) librepositoryXen.so()(64bit) ( ) sblim-gather ( =  2.2.9-33.el10) config(sblim-gather) ( =  2.2.9-33.el10) sblim-gather(x86-64) ( =  2.2.9-33.el10)"

URI_sblim-gather-devel = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sblim-gather-devel-2.2.9-33.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:sblim-gather-devel = "cim-server ( ) libgatherutil.so.0()(64bit) ( ) libmcserv.so.0()(64bit) ( ) librcserv.so.0()(64bit) ( ) librgather.so.0()(64bit) ( ) librrepos.so.0()(64bit) ( ) libgather.so.0()(64bit) ( ) librepos.so.0()(64bit) ( ) sblim-gather ( =  2.2.9-33.el10)"
RPROVIDES:sblim-gather-devel = "sblim-gather-devel ( =  2.2.9-33.el10) sblim-gather-devel(x86-64) ( =  2.2.9-33.el10)"

URI_sblim-gather-provider = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sblim-gather-provider-2.2.9-33.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:sblim-gather-provider = "/bin/sh ( ) rtld(GNU_HASH) ( ) /usr/bin/sh ( ) libc.so.6(GLIBC_2.38)(64bit) ( ) sblim-cmpi-base ( ) cim-server ( ) libgatherutil.so.0()(64bit) ( ) libmcserv.so.0()(64bit) ( ) librcserv.so.0()(64bit) ( ) librgather.so.0()(64bit) ( ) librrepos.so.0()(64bit) ( ) libcmpiOSBase_Common.so.0()(64bit) ( ) sblim-gather ( =  2.2.9-33.el10)"
RPROVIDES:sblim-gather-provider = "libOSBase_MetricDefForMEProvider.so()(64bit) ( ) libOSBase_MetricDefinitionProvider.so()(64bit) ( ) libOSBase_MetricElementCapabilitiesProvider.so()(64bit) ( ) libOSBase_MetricElementConformsToProfileProvider.so()(64bit) ( ) libOSBase_MetricForMEProvider.so()(64bit) ( ) libOSBase_MetricGathererProvider.so()(64bit) ( ) libOSBase_MetricHostedServiceProvider.so()(64bit) ( ) libOSBase_MetricIndicationProvider.so()(64bit) ( ) libOSBase_MetricInstanceProvider.so()(64bit) ( ) libOSBase_MetricLifeCycleProvider.so()(64bit) ( ) libOSBase_MetricPluginProvider.so()(64bit) ( ) libOSBase_MetricRegisteredProfileProvider.so()(64bit) ( ) libOSBase_MetricRepositoryServiceProvider.so()(64bit) ( ) libOSBase_MetricServiceAffectsElementProvider.so()(64bit) ( ) libOSBase_MetricServiceCapabilitiesProvider.so()(64bit) ( ) libOSBase_MetricServiceProvider.so()(64bit) ( ) libOSBase_MetricUtil.so.0()(64bit) ( ) libOSBase_MetricValueDefinitionProvider.so()(64bit) ( ) libOSBase_MetricValueProvider.so()(64bit) ( ) libOSBase_RepositoryPluginProvider.so()(64bit) ( ) libcimplugIPProtocolEndpoint.so()(64bit) ( ) libcimplugKvm.so()(64bit) ( ) libcimplugLocalFileSystem.so()(64bit) ( ) libcimplugNetworkPort.so()(64bit) ( ) libcimplugOperatingSystem.so()(64bit) ( ) libcimplugProcessor.so()(64bit) ( ) libcimplugUnixProcess.so()(64bit) ( ) libcimplugXen.so()(64bit) ( ) sblim-gather-provider ( =  2.2.9-33.el10) sblim-gather-provider(x86-64) ( =  2.2.9-33.el10)"

URI_sblim-gather-test = "https://vault.almalinux.org/10.0/devel/x86_64_v2/os/Packages/sblim-gather-test-2.2.9-33.el10.x86_64_v2.rpm;unpack=0"
RDEPENDS:sblim-gather-test = "/usr/bin/sh ( ) cim-server ( ) sblim-testsuite ( ) sblim-gather-provider ( =  2.2.9-33.el10)"
RPROVIDES:sblim-gather-test = "sblim-gather-test ( =  2.2.9-33.el10) sblim-gather-test(x86-64) ( =  2.2.9-33.el10)"
