#!/usr/bin/env python3

from __future__ import annotations

import logging
import tempfile

import dnf

logging.basicConfig(format='[%(levelname)s] %(message)s', level=logging.WARNING)

V = '10.0'
SECTIONS = ['BaseOS', 'AppStream', 'CRB', 'devel']
CONFS = ('src', 'bin')

cachedirs = {}
dbs = {}

with (tempfile.TemporaryDirectory() as persistdir,
      tempfile.TemporaryDirectory() as reposdir,
      tempfile.TemporaryDirectory() as cachedirs['src'],
      tempfile.TemporaryDirectory() as cachedirs['bin'],
      tempfile.TemporaryDirectory() as varsdir):
    # avoid any system configuration
    for i in CONFS:
        conf = dnf.conf.Conf()

        conf_config_file_path = conf._config.config_file_path()
        conf_config_file_path.set(value='/dev/null', priority=conf_config_file_path.getPriority())
        conf_reposdir = conf._config.reposdir()
        conf_reposdir.set(conf_reposdir.getPriority(), reposdir)
        conf_persistdir = conf._config.persistdir()
        conf_persistdir.set(conf_persistdir.getPriority(), persistdir)
        conf_system_cachedir = conf._config.system_cachedir()
        conf_system_cachedir.set(conf_system_cachedir.getPriority(), cachedirs[i])
        conf_varsdir = conf._config.varsdir()
        conf_varsdir.set(conf_varsdir.getPriority(), varsdir)

        # necessary to solve deps against concrete files
        conf._config.optional_metadata_types().getValue().push_back('load_filelists')

        dbs[i] = dnf.Base(conf=conf)

    for section in SECTIONS:
        dbs['bin'].repos.add_new_repo(section, conf, [f"https://vault.almalinux.org/{V}/{section}/x86_64_v2/os/"])
        dbs['src'].repos.add_new_repo(f"{section}-src", conf, [f"https://vault.almalinux.org/{V}/{section}/Source/"])
    dbs['bin'].fill_sack(load_system_repo=False)
    dbs['src'].fill_sack(load_system_repo=False)

    rpms_src: list[dnf.package.Package] = list(dbs['src'].sack.query().filter(latest=1).available())
    print(f"#src={len(rpms_src)}")

    pkg = rpms_src[0]
    print(f"# src: {pkg}")
    print(f'PN = "{pkg.name}"')
    print(f'PE = "{pkg.epoch}"')
    print(f'PV = "{pkg.version}"')
    print(f'PR = "{pkg.release}"')

    rpms: list[dnf.package.Package] = list(dbs['bin'].sack.query().filter(sourcerpm=f"{pkg}.rpm").available())
    print(f'PACKAGES = "{" ".join(p.name for p in rpms)}"')

    for p in rpms:
        print(f'URI_{p.name} = "{p.remote_location(schemes=["https", "http", "file"])};unpack=0"')
        rel: hawkey.Reldep
        for rel in p.requires:
            print(f"# {rel.name} {rel.relation} {rel.version}")
            providers = dbs['bin'].sack.query().filter(provides=rel)

            print(f"{rel}: {[str(p) for p in providers]}")
