## AlmaLinux 10.0 tunings

## still provides a few obsolete SRPMS

# lld, llvm
PREFERRED_RPROVIDER_lld = "llvm"
PREFERRED_RPROVIDER_lldb = "llvm"
PREFERRED_RPROVIDER_libomp = "llvm"
# clang, llvm
PREFERRED_RPROVIDER_rpm/clang-resource-filesystem = "llvm"
PREFERRED_RPROVIDER_clang-resource-filesystem = "llvm"
# libldb, samba
PREFERRED_RPROVIDER_rpm/libldb = "samba"
PREFERRED_RPROVIDER_rpm/python3-ldb = "samba"
PREFERRED_RPROVIDER_rpm/libldb-devel = "samba"
PREFERRED_RPROVIDER_libldb-devel = "samba"
PREFERRED_RPROVIDER_python3-ldb = "samba"
PREFERRED_RPROVIDER_libldb = "samba"


## break dependency loops

# 2-packages loops
RDEPENDS:redhat-rpm-config:remove = "\
python-srpm-macros \
forge-srpm-macros \
go-srpm-macros \
fonts-srpm-macros \
"
RDEPENDS:glibc-gconv-extra:remove = "glibc"
RDEPENDS:glibc-minimal-langpack:remove = "glibc"
RDEPENDS:glibc-common:remove = "glibc bash"
RDEPENDS:libxcrypt-devel:remove = "glibc-devel"
RDEPENDS:rpm-libs:remove = "rpm"
RDEPENDS:binutils-gold:remove = "binutils"
RDEPENDS:pyproject-srpm-macros:remove = "pyproject-rpm-macros"
RDEPENDS:almalinux-repos:remove = "almalinux-release"
RDEPENDS:ca-certificates:remove = "coreutils"
RDEPENDS:systemd-pam:remove = "systemd"

# 3-packages loops
RDEPENDS:redhat-rpm-config:remove = "\
pyproject-srpm-macros \
"
