## AlmaLinux 10.0 tunings

## still provides a few obsolete SRPMS

# lld, llvm
PREFERRED_RPROVIDER_lld = "llvm"
PREFERRED_RPROVIDER_lldb = "llvm"
PREFERRED_RPROVIDER_libomp = "llvm"
# clang, llvm
PREFERRED_RPROVIDER_rpm/clang-resource-filesystem = "llvm"
PREFERRED_RPROVIDER_clang-resource-filesystem = "llvm"
# libldb, samba
PREFERRED_RPROVIDER_rpm/libldb = "samba"
PREFERRED_RPROVIDER_rpm/python3-ldb = "samba"
PREFERRED_RPROVIDER_rpm/libldb-devel = "samba"
PREFERRED_RPROVIDER_libldb-devel = "samba"
PREFERRED_RPROVIDER_python3-ldb = "samba"
PREFERRED_RPROVIDER_libldb = "samba"
